# Generated by Django 4.2.1 on 2023-09-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant_store',
            old_name='name',
            new_name='m_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='p_name',
        ),
    ]
