# Generated by Django 4.2.1 on 2023-10-05 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant', '0002_rename_name_merchant_store_m_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_store',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant_store',
            name='latitude',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='merchant_store',
            name='longitude',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='merchant_store',
            name='videos',
            field=models.FileField(blank=True, upload_to='merchant_store_videos/'),
        ),
        migrations.AddField(
            model_name='products',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='product_specifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_videos',
            field=models.FileField(null=True, upload_to='product_videos/'),
        ),
        migrations.AlterField(
            model_name='merchant_store',
            name='images',
            field=models.ImageField(blank=True, upload_to='merchant_srote_images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(null=True, upload_to='product_image/'),
        ),
        migrations.CreateModel(
            name='Product_Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('feedback', models.TextField(blank=True)),
                ('rating_images', models.ImageField(upload_to='ratings_image/')),
                ('rating_video', models.FileField(upload_to='rating_video/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('shipped', 'Shipped'), ('outfordelivery', 'OutforDelivery')], default=None, max_length=20)),
                ('tracking_id', models.CharField(default=None, max_length=50)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.products')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
