# Generated by Django 4.2.1 on 2023-10-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_merchant_store_created_on_merchant_store_latitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carts',
        ),
    ]
